version: '2'
services:
  gateway-mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    # volumes are not supported on macOS
    volumes:
      - C:\Users\matortor\Desktop\mssql-volume:/var/opt/mssql/data/
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=test123!
      - MSSQL_DATABASE=folletto_test
      - MSSQL_SLEEP=60
    ports:
      - 1433:1433
    command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$MSSQL_DATABASE)"; wait;'
